language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  email: zebrap25@gmail.com
  api_key:
    secure: 2WQwCrUvDHDgmCmjQdlytq1y/dnpvSxDU7Yihjqcsp6K8Pxpt69aFazDu1LaqhXum1AiyA6CksCh0HUF2HpZlBd+iCpYIyVhtYZ9s1W1AT84jnb9x1MNv9BzXxBCpjnnLRJPlKHkn+Z0INORL4wlDzl7S1FL1Qq3jTD86DrL+kMOnfEKBY/t8ZF3naUBrZmvX0EeyJsjy2E78aXneaa8ayGKqbFl0anAavXXF0mMFd6gjA8w7MziVWLD8VHr+sZSVn0I5U8t1cK1RRaLf9S4mlusQr/9ZnVPaoGXKXVOyfFdkBxxsMEX4xzhUoMFatgcKYi3UZDu/1SRWSDJ9KBbVXUsQb6pgFzKEYHulPUbbk5x4GBJEhvHg3xxsx6fErVLY8b+6QbThpH1O1EIE2CQR1zRsVH76g6KuVjmF96xDONaTMQeCy0t467cI069p3tJTxULqED8t/PLrnX73IcAUjimWKuNTGKqoCy4YNRiKa2ibE0Dos67pxxVWWFjR3En0o72WUViu+ieA/owuewvEoGhJhKN7Xla6cMcbjQWi06aZbqoWfgtUi17TMMcLYt7raBg9X86TwnpVLaOKq9jiWd1wHStokD/bp0UdWmqgGtc5WGjC93K6SKfAEpRVosKLaXxhcDlwvRR/FvG1X4tGa8pBM0vwLMNCkGy08DHHbk=
  on:
    branch: master
