language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  email: zebrap25@gmail.com
  api_key:
    secure: xmA0Ff9OEDSBFRWjP4Z24EWI5PKZQ/8DFpXRRfn4Y7SQ2J1E9P6ou5gYJWDyflHG2HMQ4g+uCbVsjboMy7jiOZqSkR5hb3ER3EEUiD9QVCKd2y7wERJIqKN5byDilJEp91bAw4/lr6v9MdZyFl0/1MbOGAUbrMAkQu3IN7cJAJNNxV3aqRrWgWynf6G1n2w+MLzbvp5ngAwBGiQRNtwX5SM7cLfMlqoYShM+Ax9X0W7CpwE0paxH4JPlkSx9HbUjMxvLpf2N8Plzo1VEfc2o/fh6AQH/lk3Eq8UYyOE3BW67IxIblVtSB+JAorbwsgSuB5fW2rkqri7xvaB947EHo+2gv9KXhT/VBns86/L/xGUZaDO3aKn5z9CUCEYCRbdr1LZ/EBB2I7fvNV1mARkBZHBQMiy8olOKnbrNBxLuEbBkgt+e9uiyzaQRhfEmRJPxLGaguKH1PxnvuUyu2bpM9grdu0BltIfDYahgAEgny52EB7HkJty0+iZEtQmOEUknzBd4mylPpB6lexAwmTHd3/KJsqhcZZ+RjaXlYkqLeE/vwGJAgAKfm/uRYm1QAFU1gH8xEYPN+YcsH0Lay2m5G/vFkbZTBbGy3LD/dLMu3OLRp/lfRF0H4VmRki+QtSCe6ZALX4gDItrRQGzf+oOHZEfKqUZT19BQ1PS3Lmr3i/A=
  on:
    branch: master
