language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  email: zebrap25@gmail.com
  api_key:
    secure: AcdPZmucDB32cW7e/1Uc8ILs9i3sSoXrN7lrJ9MrzUrD/+TdvjM3sSq0dVexkDrLtlmay6jhgHevyEwtDI0V5XQ46H5u8Qs34BxGrHX3gHPl7E3yZ1EFQs+guS9Qk3wjIRDU1HEbYXuh71DD+GKkwwTHW9YrTZbd1yEDOOp7g2BN7nvmr8QzViY5w0MZJpjfLslLy2VxG3Xzrmxy5WRn4H+lSP9xP3q2IQy8ktCHc6wFZtQseG/SGsziH3Zjz4fuKlXroOTQ2CjKWydoEidZ5+JaeH0twzThiR0EBQunsJhyaifxnGODxCVvur9VSCYScEkOjrAyaq1+bYoEZYuYroAeJwbCrEbRxj7X++yLmuHJPXO38MIZtOjN2wwTlPj6YRt2eHZaJ4L4fELAVgEmurW1JKWnq7dB5oycCdkbOlDMC6iMLLkkRJpfaTAGiMqcdSreAhWev888ByGpqrFxT4mEenG3RCYt/1hCuJ7ZO/dhkbjyhe8q0plq9x+q+U0gXednHzxDt9pU2BB0zi3Tl1Hg+aVUl5MkcqDwH1kHZcrmPPDy6vpCO04vha/KlX0IZbZNNl0gdyQHE8NfHJ4/0rsQC3TDBJjxNJRYJk2yAcX+7gXXtThEUhVzHtibg3fsdxgFFErKRwdWNw2vJGErbC+PhgiPKQ6eS5yk/VgrOjQ=
  on:
    branch: master
